# Generated by Django 3.1.7 on 2021-03-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('tel', models.CharField(max_length=20, verbose_name='电话')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_visit', models.DateTimeField(null=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_user',
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': False, 'verbose_name': '学科', 'verbose_name_plural': '学科'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False, 'verbose_name': '老师', 'verbose_name_plural': '老师'},
        ),
    ]
